# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS



FACEBOOK_APP_ID: 491989927572515
FACEBOOK_SECRET: 3d816a97f85a8b8fc336354aeeff662c

production:
  FACEBOOK_APP_ID: 666595060048873
  FACEBOOK_SECRET: d8907b95d59e0bbc5bf615ecbd8a1385